### ISSUE TITLE
Problem running diagnostic script on new machine

### ISSUE THREAD

**Issue by hgenet** [ua-snap/dvm-dos-tem#190]
Try to run the diagnostic script and got this error:

```
helene@Quercus:scripts$ [devel] ./diagnostics.py -i 'C soil' 'C veg'
Parsing command line arguments...
Namespace(error_image=['C soil', 'C veg'], from_archive=False, plot_timeseries=False, slice='', tab_reports=False)
Creating error image plots...
Looking for json files matching pattern: /tmp/dvmdostem/calibration/monthly/*.json
Custom file slice: slice(None, None, None)
Plotting for axes 0
-------------------------------------------
Color map range for ax[0]: 820.861245185
Valid values before masking values close to zero:  539
Remaining data after masking near-zero data:  539
Traceback (most recent call last):
  File "./diagnostics.py", line 767, in <module>
    error_image(plotlist=args.error_image, fileslice=slstr)
  File "./diagnostics.py", line 177, in error_image
    image_plot(imgarrays_err, plotlist)
  File "./diagnostics.py", line 215, in image_plot
    data = data.reshape(len(data)/12, 12)
  File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 4129, in reshape
    result = self._data.reshape(*s, **kwargs).view(type(self))
ValueError: total size of new array must be unchanged

```

By the way, the python packages I have are:
```
Brlapi==0.6.1
BzrTools==2.6.0
GnuPGInterface==0.3.2
Jinja2==2.7.2
Mako==0.9.1
MarkupSafe==0.18
PAM==0.4.2
Pillow==2.3.0
PyOpenGL==3.0.2
Pygments==1.6
SecretStorage==2.0.0
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
beautifulsoup4==4.2.1
bzr==2.7.0dev1
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
configglue==1.1.2
configobj==4.7.2
cssutils==0.9.10
cvxopt==1.1.4
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
duplicity==0.6.23
git-remote-helpers==0.1.0
html5lib==0.999
httplib2==0.8
ipython==1.2.1
joblib==0.7.1
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lockfile==0.8
louis==2.5.3
lxml==3.3.3
matplotlib==1.3.1
netCDF4==1.0.6
nose==1.3.0
numpy==1.9.2
oauth==1.0.1
oauthlib==0.6.1
oneconf==0.3.7
openpyxl==1.7.0
pandas==0.18.1
paramiko==1.10.1
pexpect==3.1
piston-mini-client==0.7.5
pocketlint==0.5.31
protobuf==2.5.0
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pygpgme==0.3
pyinotify==0.9.4
pyparsing==2.0.1
pyserial==2.6
pysmbc==1.0.14.1
pysqlite==1.0.1
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
pytz==2012c
pyxdg==0.25
reportlab==3.0
requests==2.2.1
sessioninstaller==0.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.4.1
software-center-aptd-plugins==0.0.0
sympy==0.7.4.1
system-service==0.1.6
tornado==3.1.1
unity-lens-photos==1.0
urlgrabber==3.9.1
urllib3==1.7.1
virtkey==0.63.0
virtualenv==1.10.1
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xdiagnose==3.6.3build2
xkit==0.0.0
xlrd==0.9.2
xlwt==0.7.5
yum-metadata-parser==1.1.4
zope.interface==4.0.5

```

**Comment by tobeycarman** [comment]
shoot, working on my machine. I have `matplotlib 1.4.x`. Maybe try upgrading matplotlib:

`pip install matplotlib --upgrade`

**Comment by hgenet** [comment]
JFILES IS NOT SORTED check line 109 !

**Comment by hgenet** [comment]
Tobey fixed the problem - related to json files not being properly sorted.
