### ISSUE TITLE
Invisible plot lines following OS and package updates

### ISSUE THREAD

**Issue by rarutter** [ua-snap/dvm-dos-tem#250]
On a fresh install of Fedora 25 with all packages necessary to run dvmdostem, the model runs fine, but the calibration viewer only displays plot lines while the window is being resized. If the window is static, the plot lines disappear. In addition, when the suite is changed using the radio buttons, the following error occurs:
```
Parsing command line arguments...
Setting up logging...
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 587, in callit
    func(*args)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 147, in _on_timer
    TimerBase._on_timer(self)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 1305, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/animation.py", line 1049, in _step
    still_going = Animation._step(self, *args)
  File "/usr/lib64/python2.7/site-packages/matplotlib/animation.py", line 855, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/lib64/python2.7/site-packages/matplotlib/animation.py", line 875, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "/usr/lib64/python2.7/site-packages/matplotlib/animation.py", line 898, in _post_draw
    self._blit_draw(self._drawn_artists, self._blit_cache)
  File "/usr/lib64/python2.7/site-packages/matplotlib/animation.py", line 913, in _blit_draw
    a.axes.draw_artist(a)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 2334, in draw_artist
    raise AttributeError(msg)
AttributeError: draw_artist can only be used after an initial draw which caches the render
```

**Comment by tobeycarman** [comment]
Hmm, this seems like it might be an annoying and tricky issue to deal
with...

**Comment by tobeycarman** [comment]
Any more clues if you try `--loglevel=debug`?

**Comment by rarutter** [comment]
Yeah, this is going to be interesting. I'm going to talk to Helene about remote access so I can keep messing with it (the laptop is in FAI).
