### ISSUE TITLE
calibration-viewer.py error when running new CMT with parameter files in alternate places.

### ISSUE THREAD

**Issue by tobeycarman** [ua-snap/dvm-dos-tem#334]
The problem occurs when the user is trying to run the calibration viewer (and the model) from a directory other than the main repo and the user has added a new CMT that does not exist in the default parameter directories. In this case, the calibration viewer looks toward the main repo to find the calibration_targets.py file and the cmt_calparbgc.txt file for looking up PFT "long names" for display as background text.

For example, with this directory structure:
```
~/experimentA/
    parameters/
        cmt_calparbgc.txt   # <-- has new CMT type not found in main repo!!
    config/
        config.js  # <--  points to local parameters directory


~/dvm-dos-tem/
    ...
    calibration/
        calibration_targets.py
        calibration-viewer.py
        ...
    parameters/
        cmt_calparbgc.txt
        ...
```

And then these calls:

```
cd ~/experimentA
../dvm-dos-tem/dvmdostem --cal-mode

../dvm-dos-tem/calibration/calibration-viewer.py
```

Will result in this:
```
...
INFO    dataloader Load tmp data for every trace to trace's line
INFO    dataloader Recomputing data limits based on artist data
INFO    dataloader Force draw after autoscale
INFO    dataloader Finished loading data.
INFO    root     Clearing all the background 'PFTx' texts
INFO    root     Set the background 'PFTx' text for axes that are plotting pft specific variables.
DEBUG   __main__ Setting the verbose name for the PFT!
Traceback (most recent call last):
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/calibration-viewer.py", line 1262, in <module>
    extrainput=additional_input_helpers
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/calibration-viewer.py", line 392, in __init__
    self.setup_axes_ticks_events_and_load_data()
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/calibration-viewer.py", line 653, in setup_axes_ticks_events_and_load_data
    self.load_data2plot(relim=True, autoscale=True)
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/calibration-viewer.py", line 566, in load_data2plot
    self.set_bg_pft_txt()
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/calibration-viewer.py", line 900, in set_bg_pft_txt
    vname = "(%s)" % pu.get_pft_verbose_name(pftkey=trace['pft'], cmtkey=cmtkey)
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/../scripts/param_util.py", line 170, in get_pft_verbose_name
    data = get_CMT_datablock(os.path.join(path2params, 'cmt_calparbgc.txt'), cmtnum)
  File "/Users/tobeycarman/Documents/SEL/dvm-dos-tem/calibration/../scripts/param_util.py", line 118, in get_CMT_datablock
    end = startidx + i
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by tobeycarman** [comment]
At this point, it seems like a decent solution might be command line flags for the calibration-viewer that allow the user to set the parameter directory where the viewer will look for the PFT "long names".

**Comment by tobeycarman** [comment]
Maybe the calibration-viewer.py should ingest the config file??
